## configure exporter here

mysql:
  # db: ""
  host: "mysql.database-monitoring.svc.cluster.local" # mysql =service_name from mysql-service.yaml and mysql.database-monitoring.svc.cluster.local is the internal DNS name of a MySQL Service
  user: "mysqluser"
  # pass: "password"
  port: 3306
  existingPasswordSecret:
    name: "mysql-secret"
    key: "MYSQL_PASSWORD"

serviceMonitor:
  # enabled should be set to true to enable prometheus-operator discovery of this service
  enabled: true
  apiVersion: "monitoring.coreos.com/v1"
  # interval is the interval at which metrics should be scraped
  interval: 30s
  # scrapeTimeout is the timeout after which the scrape is ended
  scrapeTimeout: 10s
  namespace: monitoring
  # namespaceSelector: []
  # additionalLabels is the set of additional labels to add to the ServiceMonitor
  additionalLabels:
    release: prometheus # use this to be discovered by prometheus-operator

